services:
  - type: worker
    name: telegram-manager-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DEFAULT_TIMEZONE
        value: Europe/Berlin
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-manager-db
          property: connectionString

databases:
  - name: telegram-manager-db
    plan: free
