services:
  - type: worker
    name: telegram-manager-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DEFAULT_TIMEZONE
        value: Europe/Tehran
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: SESSION_SECRET
        sync: false
